### ISSUE TITLE
Consolidate webcam and terminal

### ISSUE THREAD

**Issue by OmiCron07** [jneilliii/OctoPrint-ConsolidateTempControl#14]
Would be nice to view the webcam while doing g-code in terminal.

**Comment by jneilliii** [comment]
I've been considering making a more generic tab combine plugin.

**Comment by jlwainwright** [comment]
> Would be nice to view the webcam while doing g-code in terminal.

Or even the option to just add the Terminal to the consolidated tab as well?

**Comment by jneilliii** [comment]
If you guys want to test out my ConsolidatedTabs version, I think it's almost ready for official release and would be good to get some feedback. You can find it at the link below. Please post any issues you may have in that repository.

https://github.com/jneilliii/OctoPrint-ConsolidatedTabs
