### ISSUE TITLE
Feature Request: Hide Graph and Webcam

### ISSUE THREAD

**Issue by Bootscreen** [jneilliii/OctoPrint-ConsolidateTempControl#15]
Hey,

is it possible to get an option to hide the webcam and the graph?
I have both on my second sidebar and doesn't need it twice ^^

**Comment by jneilliii** [comment]
That's an odd request honestly. I don't think I'd incorporate that in this plugin, but I don't think it would be too difficult to write this as a separate plugin.

**Comment by jneilliii** [comment]
@Bootscreen you don't by chance utilize Themeify do you? If so you could achieve this with that plugin.

**Comment by Bootscreen** [comment]
I use themify. Can you explain it?

**Comment by jneilliii** [comment]
Sure, in Themeify if you add the following to your advanced section it will hide those objects you mentioned.

| Selector           | CSS-Rule | Value |
|--------------------|----------|-------|
| #temperature-graph | display  | none  |
| #webcam_container  | display  | none  |

**Comment by jneilliii** [comment]
Since this is possible with Themeify I'm closing this ticket.
