### ISSUE TITLE
after updating plugin, OctoPrint is in a "refresh UI" loop

### ISSUE THREAD

**Issue by dagnabbit99** [jneilliii/OctoPrint-ConsolidateTempControl#17]
After updating the plugin this morning, and rebooting the Pi, the OctoPrint UI went into a refresh loop- "ConsolidateTempControl has changed layout, refresh UI".  Tried rebooting, closing out the browser tab and opening a enw one, shutting down the browwser and restarting, and trying a different browser.  Had to manually uninstall using pip in an SSH session.

**Comment by Dalewn** [comment]
Have had the same issue.
I managed to exit the loop by clicking on the wrench to open the settings before it was able to request the refresh. I think the settings dialog actually disables this popup.

Can provide debug logs later today, if this will help.

**Comment by jneilliii** [comment]
Thanks for the reports guys. I have reverted the releases 0.1.5 and 0.1.6 from the updater. The default install will still show this issue possibly, but will need to investigate further after getting off work. My initial testing wasn't having this issue. Can you provide lists of what other plugins you have installed?

**Comment by jneilliii** [comment]
Also, what version were you guys upgrading from it you know? I had released two versions back to back and wonder if that might have been causing some issues.

**Comment by jneilliii** [comment]
I just pushed an update to the master branch. If you could install again from Plugin Manager and let me know if this issue still remains or not that would be great. It will show as version 0.1.7 once installed.

**Comment by SimonFransen** [comment]
I had this problem. You can just press the escape key to close the warning.
Uninstalling and installing 0.1.7 fixed this for me.

**Comment by jneilliii** [comment]
Thanks, that's good news. I'll push this release official.

**Comment by Dalewn** [comment]
@SimonFransen Sounds good! Also, I didn't know you could close it with ESC.

@jneilliii Will give it a shot later, sorry. I'm currently running quite a long print...

**Comment by dagnabbit99** [comment]
working great now, thanks!
