### ISSUE TITLE
Support for dual extruders

### ISSUE THREAD

**Issue by Z0t** [jneilliii/OctoPrint-ConsolidateTempControl#18]
Love the interface, but it does not seems to  support dual extruders.

**Comment by jneilliii** [comment]
Not quite sure what you mean. The plugin just moves the standard octoprint tabs into the one tab, so everything should be as is with the standard octoprint tab.

**Comment by Z0t** [comment]
Hmm, I took screen shots, then disabled the plugin, restarted the server (Break/run) took more screenshots of the dual enabled dialogs, re-enabled the plugin, restarted and now it works fine. 

 I installed by pip on the command line restarted after killing the server with Ctrl-C  (CentOS).  So there may be an issue on installation.  When I initially installed my default printer was reset to the single profile.  I selected the dual profile and restarted in the same way (break, rerun). and that still showed me single extruders.  Someone was weird there...
