### ISSUE TITLE
FYI conflict with snapstream plugin (includes resolution)

### ISSUE THREAD

**Issue by tonysurma** [jneilliii/OctoPrint-ConsolidateTempControl#19]
Makes sense as it removes and consolidates the tabs but the [SnapStream plugin](https://github.com/markwal/OctoPrint-SnapStream) that replaces the stream with an auto refreshing jpeg snapshot can't find the camera feed in the new consolidated tab.

So no issue in your plugin but FYI that it breaks the other.  As that project hasn't been touched in 4 years I made a quick fork and made a minor update to work with this plugin.  If anyone is/wants to use these two together there is a fix in out there in [this release on my fork](https://github.com/tonysurma/OctoPrint-SnapStream/releases/tag/0.2.5) that can be loaded into plugin manager [directly](https://github.com/tonysurma/OctoPrint-SnapStream/archive/0.2.5.zip)

**Comment by jneilliii** [comment]
@markwal is still active, you could probably just submit a PR to his repo and he would more than likely merge it.
