### ISSUE TITLE
UI isses when active with "UI Customizer"

### ISSUE THREAD

**Issue by holocronology** [jneilliii/OctoPrint-ConsolidateTempControl#21]
I originally reported this over [here](https://github.com/OctoPrint/OctoPrint/issues/3850). But I was confused and thought it was installed as part of the 1.5.0 update.

I've been trying to continue troubleshoot this and I've noticed that UI issues are present when Consolidate Temp Control is active when UI Customizer is active. Both function normally in the absence of the other.

I removed this plug-in and everything was OK. Then, upon trying to reinstall Consolidate Temp Control, it would not install or show up. It [appears to install correctly](https://i.imgur.com/K8N2VOt.png), but after restarting, it is not active and does not show up in the plug-in list.

Maybe it's being replaced by the Consolidated Tabs?

**Comment by jneilliii** [comment]
Have you also cross posted an issue yet in ui customizer repo? I'm not 100% sure right now, from memory, why the two plugins wouldn't play nicely together, but I'll have to look further into how that plugin is doing its ui mods. This plugin should only be moving the temp and control tab content into one tab.

**Comment by holocronology** [comment]
I have not cross posted this into the other repo yet. Perhaps a bit new to this, I figured posting in what seemed to be the repo behaving badly. But I will drop it in the other one as well.

**Comment by LazeMSS** [comment]
Yes in general theses plugins can collide. It's hard to combine everything when one plugin is not aware of the other.

It's not a bug as I see it but more a choice of which plugins fits your needs the best.

**Comment by LazeMSS** [comment]
I also think this should be closed as it seems to be working for the reporter now

**Comment by holocronology** [comment]
Still being weird on Horizontal layout.

https://i.imgur.com/RVNv1ck.png

**Comment by jneilliii** [comment]
Nice, the other plugin added a notice.

**Comment by jneilliii** [comment]
Vertical mode may work better.

**Comment by holocronology** [comment]
Vertical mode does work better. I opted to use the Consolidated Tabs plugin, in place of Consolidated Temp Control.
