### ISSUE TITLE
Would like to overlay temperature graph with webcam

### ISSUE THREAD

**Issue by jgrills** [jneilliii/OctoPrint-ConsolidateTempControl#22]
I saw a prototype of it in this post https://community.octoprint.org/t/temperature-graph-next-to-webcam-in-control-tab/2074/11 and it looked great and saved tons of screen space.

**Comment by jneilliii** [comment]
Why don't you just install my other plugin, linked in the post just after that?

**Comment by jneilliii** [comment]
https://github.com/jneilliii/OctoPrint-WebcamTempGraph

**Comment by jgrills** [comment]
It wasn't available through the plugin manager so I was less confident in it. But I'll try it out.

**Comment by jgrills** [comment]
If I do what you suggest with this plugin so I get all my controls on one page, I end up with two webcam images.

**Comment by jneilliii** [comment]
Ok, I think I understand what you are actually requesting now. You want to combine both tabs and then squish the webcam into the temperature graph? Add the webcam tab plugin and it will remove the default webcam from the control tab and give you what you want I think. But then your stick with additional tab you might not want.

**Comment by JasonLooseArrow** [comment]
I like where you guys are going with this.

**Comment by jgrills** [comment]
Here's what my "main" page of octoprint presently looks like for me. 

![image](https://user-images.githubusercontent.com/10910379/103184953-db2ae500-487f-11eb-86df-92d848d6c927.png)

I did some quick image editing to express exactly what I was hoping to achieve, kept the image the same size so it makes clear how much vertical room was recovered.

![image](https://user-images.githubusercontent.com/10910379/103184999-0dd4dd80-4880-11eb-8b03-f912eb3d3aae.png)

**Comment by jneilliii** [comment]
Yeah, that's kind of what I thought. Moving the temp controls below the other controls might be more difficult, but hiding the webcam on the control tab part and putting the image in the background of the temp graph is definitely possible. Technically since you have themeify tou could do this with its advanced customization options and just make the default webcam display css value none I think and use that other plugin to replace the temp graph (or do that in themeify too).

**Comment by jneilliii** [comment]
```
Selector:    #temperature-graph
CSS-Rule:    background
Value:       url(/webcam/?action=stream) no-repeat center

Selector:    #webcam_container
CSS-Rule:   display
Value: none
```

**Comment by jgrills** [comment]
A little more tweaking and now it's perfect! Everything I generally need on one page, no scrolling. Thanks so much! 
![image](https://user-images.githubusercontent.com/10910379/103335474-a1eaa480-4a3a-11eb-86ee-8b0446b83d47.png)
