### ISSUE TITLE
Unable to send prints to printer from PrusaSlicer

### ISSUE THREAD

**Issue by astanix** [jneilliii/OctoPrint-ConsolidateTempControl#23]
When this plugin is installed and active the following error is produced from click send to printer on Prusa.
Disabling the plugin fixes the issue with Prusa.

Error uploading to print host:
HTTP 500: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by jneilliii** [comment]
Could you please share your octoprint.log file, because my plugin shouldn't interfere with the file upload API at all.
