### ISSUE TITLE
Cannot select / copy text from Octoklipper

### ISSUE THREAD

**Issue by Sineos** [jneilliii/OctoPrint-ConsolidateTempControl#24]
Firstly, many thanks for this plugin. It is really useful, especially with big screens.

I have one small issue:
When using this plugin, I can no longer select or copy text from the octoklipper plugin window. Not a show stopper but would be cool to have it back. Thanks for considering.

**Comment by jneilliii** [comment]
I'll see what I can do to resolve this.

**Comment by Sineos** [comment]
My apologies. I meant your consolidated tabs plugin and not the temp control one.
