### ISSUE TITLE
Request, not issue

### ISSUE THREAD

**Issue by prostang** [jneilliii/OctoPrint-ConsolidateTempControl#27]
Would it be possible to put the current Z position somewhere in the UI?  I installed this add-in and love it, but it doesn't allow for any other UI-based add-ins to work, such as a Z position one I just installed.

Thanks for such great work!!!!

**Comment by jneilliii** [comment]
can you share the link to this plugin in question? Usually it's easier to fix conflict than implement additional features and go outside of the scope of what the plugin's intended purpose.

**Comment by prostang** [comment]
https://plugins.octoprint.org/plugins/displayz/

**Comment by jneilliii** [comment]
I am unable to reproduce an issue with that other plugin. I installed both that one and this one and I am able to see the modifications that are done by that plugin in the UI, see screenshot below (highlighted area is added by displayz). 

![image](https://user-images.githubusercontent.com/5249455/207423370-818e8bee-9d4d-4c06-8f04-dc1061e21d09.png)

**Comment by prostang** [comment]
Yes.  I powered down my Raspberry PI and booted it back up and I am now seeing what you have in the image.  Sorry about that.
