### ISSUE TITLE
Temperature tab is still visible in Octoprint 1.3.1

### ISSUE THREAD

**Issue by NovaViper** [jneilliii/OctoPrint-ConsolidateTempControl#4]
Hi! I just recently downloaded the plugin but I noticed that the temperature tab is still visible (but the controls tab is gone). I even took out DragOnOrder and TabOrder just to see if that fixes it but it doesn't. I have many other plugins, but the only one that messes with the CSS of Octoprint is Themeify

**Comment by jneilliii** [comment]
This is related to #1 I believe.  Anytime the tabs are re-ordered it messes this plugin up. Closing as duplicate.

**Comment by NovaViper** [comment]
I just noticed that 0.1.3b fixes this issue

**Comment by jneilliii** [comment]
Oh yeah, I think I did incorporate a fix for that by updating the settings_overlay callback.

**Comment by Warchildz** [comment]
Hello I am having this issue now too, However I can not find version 0.13b......

**Comment by jneilliii** [comment]
You can install the 0.13b version using the link below in plugin manager.

https://github.com/jneilliii/OctoPrint-ConsolidateTempControl/archive/0.1.3b.zip

**Comment by Warchildz** [comment]
Thank you worked!!!
